// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package main

import "strings"

type GetUserByNameEndpoint struct{}

func (p GetUserByNameEndpoint) Path(username string) string {
	message := "/user/{username}"
	message = strings.Replace(message, "{username}", username, -1)
	return message
}

type LogoutUserEndpoint struct{}

func (p LogoutUserEndpoint) Path() string {
	message := "/user/logout"
	return message
}

type LoginUserEndpoint struct{}

func (p LoginUserEndpoint) Path() string {
	message := "/user/login"
	return message
}

type GetOrderByIdEndpoint struct{}

func (p GetOrderByIdEndpoint) Path(orderId string) string {
	message := "/store/order/{orderId}"
	message = strings.Replace(message, "{orderId}", orderId, -1)
	return message
}

type GetInventoryEndpoint struct{}

func (p GetInventoryEndpoint) Path() string {
	message := "/store/inventory"
	return message
}

type GetPetByIdEndpoint struct{}

func (p GetPetByIdEndpoint) Path(petId string) string {
	message := "/pet/{petId}"
	message = strings.Replace(message, "{petId}", petId, -1)
	return message
}

type FindPetsByTagsEndpoint struct{}

func (p FindPetsByTagsEndpoint) Path() string {
	message := "/pet/findByTags"
	return message
}

type FindPetsByStatusEndpoint struct{}

func (p FindPetsByStatusEndpoint) Path() string {
	message := "/pet/findByStatus"
	return message
}

type Paths struct {
	GetInventoryEndpoint     GetInventoryEndpoint
	GetPetByIdEndpoint       GetPetByIdEndpoint
	FindPetsByTagsEndpoint   FindPetsByTagsEndpoint
	FindPetsByStatusEndpoint FindPetsByStatusEndpoint
	GetUserByNameEndpoint    GetUserByNameEndpoint
	LogoutUserEndpoint       LogoutUserEndpoint
	LoginUserEndpoint        LoginUserEndpoint
	GetOrderByIdEndpoint     GetOrderByIdEndpoint
}
