// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package main

import "strings"

type GetUserByNameParam struct{}

func (p GetUserByNameParam) Path(username string) string {
	message := "/user/{username}"
	message = strings.Replace(message, "{username}", username, -1)
	return message
}

type LogoutUserParam struct{}

func (p LogoutUserParam) Path() string {
	message := "/user/logout"
	return message
}

type LoginUserParam struct{}

func (p LoginUserParam) Path() string {
	message := "/user/login"
	return message
}

type GetOrderByIdParam struct{}

func (p GetOrderByIdParam) Path(orderId string) string {
	message := "/store/order/{orderId}"
	message = strings.Replace(message, "{orderId}", orderId, -1)
	return message
}

type GetInventoryParam struct{}

func (p GetInventoryParam) Path() string {
	message := "/store/inventory"
	return message
}

type GetPetByIdParam struct{}

func (p GetPetByIdParam) Path(petId string) string {
	message := "/pet/{petId}"
	message = strings.Replace(message, "{petId}", petId, -1)
	return message
}

type FindPetsByTagsParam struct{}

func (p FindPetsByTagsParam) Path() string {
	message := "/pet/findByTags"
	return message
}

type FindPetsByStatusParam struct{}

func (p FindPetsByStatusParam) Path() string {
	message := "/pet/findByStatus"
	return message
}

type Paths struct {
	FindPetsByTagsParam   FindPetsByTagsParam
	FindPetsByStatusParam FindPetsByStatusParam
	GetUserByNameParam    GetUserByNameParam
	LogoutUserParam       LogoutUserParam
	LoginUserParam        LoginUserParam
	GetOrderByIdParam     GetOrderByIdParam
	GetInventoryParam     GetInventoryParam
	GetPetByIdParam       GetPetByIdParam
}
