// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package main

import (
	"net/url"
	"strings"
)

type FindPetsByStatusEndpoint struct{}

type FindPetsByStatusEndpointQueryParams struct {
	Status string
}

func (q FindPetsByStatusEndpointQueryParams) ToQueryString() string {
	values := url.Values{}
	if q.Status != "" {
		values.Set("status", q.Status)
	}
	return values.Encode()
}

func (p FindPetsByStatusEndpoint) Path(queryParams FindPetsByStatusEndpointQueryParams) string {
	message := "/pet/findByStatus"
	if queryString := queryParams.ToQueryString(); queryString != "" {
		message = message + "?" + queryString
	}
	return message
}

type FindPetsByTagsEndpoint struct{}

type FindPetsByTagsEndpointQueryParams struct {
	Tags []string
}

func (q FindPetsByTagsEndpointQueryParams) ToQueryString() string {
	values := url.Values{}
	for _, v := range q.Tags {
		values.Add("tags", v)
	}
	return values.Encode()
}

func (p FindPetsByTagsEndpoint) Path(queryParams FindPetsByTagsEndpointQueryParams) string {
	message := "/pet/findByTags"
	if queryString := queryParams.ToQueryString(); queryString != "" {
		message = message + "?" + queryString
	}
	return message
}

type GetPetByIdEndpoint struct{}

func (p GetPetByIdEndpoint) Path(petId string) string {
	message := "/pet/{petId}"
	message = strings.Replace(message, "{petId}", petId, -1)
	return message
}

type GetInventoryEndpoint struct{}

func (p GetInventoryEndpoint) Path() string {
	message := "/store/inventory"
	return message
}

type GetOrderByIdEndpoint struct{}

func (p GetOrderByIdEndpoint) Path(orderId string) string {
	message := "/store/order/{orderId}"
	message = strings.Replace(message, "{orderId}", orderId, -1)
	return message
}

type LoginUserEndpoint struct{}

type LoginUserEndpointQueryParams struct {
	Username string
	Password string
}

func (q LoginUserEndpointQueryParams) ToQueryString() string {
	values := url.Values{}
	if q.Username != "" {
		values.Set("username", q.Username)
	}
	if q.Password != "" {
		values.Set("password", q.Password)
	}
	return values.Encode()
}

func (p LoginUserEndpoint) Path(queryParams LoginUserEndpointQueryParams) string {
	message := "/user/login"
	if queryString := queryParams.ToQueryString(); queryString != "" {
		message = message + "?" + queryString
	}
	return message
}

type LogoutUserEndpoint struct{}

func (p LogoutUserEndpoint) Path() string {
	message := "/user/logout"
	return message
}

type GetUserByNameEndpoint struct{}

func (p GetUserByNameEndpoint) Path(username string) string {
	message := "/user/{username}"
	message = strings.Replace(message, "{username}", username, -1)
	return message
}

type Paths struct {
	FindPetsByStatusEndpoint FindPetsByStatusEndpoint
	FindPetsByTagsEndpoint   FindPetsByTagsEndpoint
	GetInventoryEndpoint     GetInventoryEndpoint
	GetOrderByIdEndpoint     GetOrderByIdEndpoint
	GetPetByIdEndpoint       GetPetByIdEndpoint
	GetUserByNameEndpoint    GetUserByNameEndpoint
	LoginUserEndpoint        LoginUserEndpoint
	LogoutUserEndpoint       LogoutUserEndpoint
}
