// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package main

import "strings"

type GetUsersEndpoint struct{}

func (p GetUsersEndpoint) Path() string {
	message := "/api/v1/users"
	return message
}

type GetUserEndpoint struct{}

func (p GetUserEndpoint) Path(userId string) string {
	message := "/api/v1/users/{userId}"
	message = strings.Replace(message, "{userId}", userId, -1)
	return message
}

type ActuatorsInfoEndpoint struct{}

func (p ActuatorsInfoEndpoint) Path() string {
	message := "/actuators/info"
	return message
}

type ActuatorsHealthEndpoint struct{}

func (p ActuatorsHealthEndpoint) Path() string {
	message := "/actuators/health"
	return message
}

type Paths struct {
	GetUserEndpoint         GetUserEndpoint
	ActuatorsInfoEndpoint   ActuatorsInfoEndpoint
	ActuatorsHealthEndpoint ActuatorsHealthEndpoint
	GetUsersEndpoint        GetUsersEndpoint
}
