// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package main

import (
	"net/url"
	"strings"
)

type ActuatorsHealthEndpoint struct{}

func (p ActuatorsHealthEndpoint) Path() string {
	message := "/actuators/health"
	return message
}

type ActuatorsInfoEndpoint struct{}

func (p ActuatorsInfoEndpoint) Path() string {
	message := "/actuators/info"
	return message
}

type GetUsersEndpoint struct{}

type GetUsersEndpointQueryParams struct {
	Page string
	Size string
}

func (q GetUsersEndpointQueryParams) ToQueryString() string {
	values := url.Values{}
	if q.Page != "" {
		values.Set("page", q.Page)
	}
	if q.Size != "" {
		values.Set("size", q.Size)
	}
	return values.Encode()
}

func (p GetUsersEndpoint) Path(queryParams GetUsersEndpointQueryParams) string {
	message := "/api/v1/users"
	if queryString := queryParams.ToQueryString(); queryString != "" {
		message = message + "?" + queryString
	}
	return message
}

type GetUserEndpoint struct{}

type GetUserEndpointQueryParams struct {
	Fields []string
}

func (q GetUserEndpointQueryParams) ToQueryString() string {
	values := url.Values{}
	if len(q.Fields) > 0 {
		values.Set("fields", strings.Join(q.Fields, ","))
	}
	return values.Encode()
}

func (p GetUserEndpoint) Path(userId string, queryParams GetUserEndpointQueryParams) string {
	message := "/api/v1/users/{userId}"
	message = strings.Replace(message, "{userId}", userId, -1)
	if queryString := queryParams.ToQueryString(); queryString != "" {
		message = message + "?" + queryString
	}
	return message
}

type Paths struct {
	ActuatorsHealthEndpoint ActuatorsHealthEndpoint
	ActuatorsInfoEndpoint   ActuatorsInfoEndpoint
	GetUserEndpoint         GetUserEndpoint
	GetUsersEndpoint        GetUsersEndpoint
}
