package internal

import (
	"fmt"

	"github.com/dave/jennifer/jen"
)

// GenerateFile generates the file based on the paths.
func GenerateFile(paths []Path, c Cfg) (*jen.File, error) {
	f := jen.NewFile(c.PackageName())
	f.HeaderComment("Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.")

	structsCreated := make(map[string]Path)
	for _, p := range paths {
		err := generatePath(f, p, structsCreated)
		if err != nil {
			return nil, err
		}
	}

	fields := make([]jen.Code, 0)
	for field := range structsCreated {
		fields = append(fields, jen.Id(field).Id(field))
	}

	f.Type().Id("Paths").Struct(fields...)

	return f, nil
}

func generatePath(f *jen.File, path Path, structsCreated map[string]Path) error {
	structName := path.AddEndpointStruct(f)
	if _, ok := structsCreated[structName]; ok {
		return fmt.Errorf("struct name already used: %q", structName)
	}

	structsCreated[structName] = path

	return nil
}
